#include "Flags.h"

Flags::Flags() : Module("Flags", "idk", Category::WORLD) {
    registerSetting(new BoolSetting("Onfire", "Sets the player on fire", &onfire, false));
    registerSetting(new BoolSetting("Sneaking", "Enables sneaking", &sneaking, false));
    registerSetting(new BoolSetting("Riding", "Sets riding state", &riding, false));
    registerSetting(new BoolSetting("Sprinting", "Enables sprinting", &sprinting, false));
    registerSetting(new BoolSetting("UsingItem", "Sets using item state", &usingitem, false));
    registerSetting(new BoolSetting("Invisible", "Makes player invisible", &invisible, false));
    registerSetting(new BoolSetting("Tempted", "Sets tempted state", &tempted, false));
    registerSetting(new BoolSetting("Inlove", "Sets in love state", &inlove, false));
    registerSetting(new BoolSetting("Saddled", "Sets saddled state", &saddled, false));
    registerSetting(new BoolSetting("Powered", "Sets powered state", &powered, false));
    registerSetting(new BoolSetting("Ignited", "Sets ignited state", &ignited, false));
    registerSetting(new BoolSetting("Baby", "Sets baby state", &baby, false));
    registerSetting(new BoolSetting("Converting", "Sets converting state", &converting, false));
    registerSetting(new BoolSetting("Critical", "Sets critical hit state", &critical, false));
    registerSetting(new BoolSetting("CanShowName", "Allows name display", &canShowName, false));
    registerSetting(new BoolSetting("AlwaysShowName", "Always shows name", &alwaysShowName, false));
    registerSetting(new BoolSetting("NoAI", "Disables AI", &noai, false));
    registerSetting(new BoolSetting("Silent", "Sets silent state", &silent, false));
    registerSetting(new BoolSetting("Wallclimbing", "Enables wall climbing", &wallclimbing, false));
    registerSetting(new BoolSetting("CanClimb", "Allows climbing", &canclimb, false));
    registerSetting(new BoolSetting("CanSwim", "Allows swimming", &canswim, false));
    registerSetting(new BoolSetting("CanFly", "Allows flying", &canfly, false));
    registerSetting(new BoolSetting("CanWalk", "Allows walking", &canwalk, false));
    registerSetting(new BoolSetting("Resting", "Sets resting state", &resting, false));
    registerSetting(new BoolSetting("Sitting", "Sets sitting state", &sitting, false));
    registerSetting(new BoolSetting("Angry", "Sets angry state", &angry, false));
    registerSetting(new BoolSetting("Interested", "Sets interested state", &interested, false));
    registerSetting(new BoolSetting("Charged", "Sets charged state", &charged, false));
    registerSetting(new BoolSetting("Tamed", "Sets tamed state", &tamed, false));
    registerSetting(new BoolSetting("Orphaned", "Sets orphaned state", &orphaned, false));
    registerSetting(new BoolSetting("Leashed", "Sets leashed state", &leashed, false));
    registerSetting(new BoolSetting("Sheared", "Sets sheared state", &sheared, false));
    registerSetting(new BoolSetting("Gliding", "Enables gliding", &gliding, false));
    registerSetting(new BoolSetting("Elder", "Sets elder state", &elder, false));
    registerSetting(new BoolSetting("Moving", "Sets moving state", &moving, false));
    registerSetting(new BoolSetting("Breathing", "Sets breathing state", &breathing, false));
    registerSetting(new BoolSetting("Chested", "Sets chested state", &chested, false));
    registerSetting(new BoolSetting("Stackable", "Sets stackable state", &stackable, false));
    registerSetting(new BoolSetting("ShowBottom", "Shows bottom", &showBottom, false));
    registerSetting(new BoolSetting("Standing", "Sets standing state", &standing, false));
    registerSetting(new BoolSetting("Shaking", "Sets shaking state", &shaking, false));
    registerSetting(new BoolSetting("Idling", "Sets idling state", &idling, false));
    registerSetting(new BoolSetting("Casting", "Sets casting state", &casting, false));
    registerSetting(new BoolSetting("Charging", "Sets charging state", &charging, false));
    registerSetting(new BoolSetting("WasdControlled", "Enables WASD control", &wasdControlled, false));
    registerSetting(new BoolSetting("CanPowerJump", "Allows power jumping", &canPowerJump, false));
    registerSetting(new BoolSetting("CanDash", "Allows dashing", &canDash, false));
    registerSetting(new BoolSetting("Lingering", "Sets lingering state", &lingering, false));
    registerSetting(new BoolSetting("HasCollision", "Enables collision", &hasCollision, false));
    registerSetting(new BoolSetting("HasGravity", "Enables gravity", &hasGravity, false));
    registerSetting(new BoolSetting("FireImmune", "Sets fire immunity", &fireImmune, false));
    registerSetting(new BoolSetting("Dancing", "Sets dancing state", &dancing, false));
    registerSetting(new BoolSetting("Enchanted", "Sets enchanted state", &enchanted, false));
    registerSetting(new BoolSetting("ReturnTrident", "Enables trident return", &returntrident, false));
    registerSetting(new BoolSetting("ContainerIsPrivate", "Sets private container", &containerIsPrivate, false));
    registerSetting(new BoolSetting("IsTransforming", "Sets transforming state", &isTransforming, false));
    registerSetting(new BoolSetting("DamageNearbyMobs", "Damages nearby mobs", &damagenearbymobs, false));
    registerSetting(new BoolSetting("Swimming", "Sets swimming state", &swimming, false));
    registerSetting(new BoolSetting("Bribed", "Sets bribed state", &bribed, false));
    registerSetting(new BoolSetting("IsPregnant", "Sets pregnant state", &isPregnant, false));
    registerSetting(new BoolSetting("LayingEgg", "Sets egg-laying state", &layingEgg, false));
    registerSetting(new BoolSetting("PassengerCanPick", "Allows passenger to pick", &passengerCanPick, false));
    registerSetting(new BoolSetting("TransitionSitting", "Sets transition sitting state", &transitionSitting, false));
    registerSetting(new BoolSetting("Eating", "Sets eating state", &eating, false));
    registerSetting(new BoolSetting("LayingDown", "Sets laying down state", &layingDown, false));
    registerSetting(new BoolSetting("Sneezing", "Sets sneezing state", &sneezing, false));
    registerSetting(new BoolSetting("Trusting", "Sets trusting state", &trusting, false));
    registerSetting(new BoolSetting("Rolling", "Sets rolling state", &rolling, false));
    registerSetting(new BoolSetting("Scared", "Sets scared state", &scared, false));
    registerSetting(new BoolSetting("InScaffolding", "Sets in scaffolding state", &inScaffolding, false));
    registerSetting(new BoolSetting("OverScaffolding", "Sets over scaffolding state", &overScaffolding, false));
    registerSetting(new BoolSetting("DescendThroughBlock", "Allows descending through blocks", &descendThroughBlock, false));
    registerSetting(new BoolSetting("Blocking", "Sets blocking state", &blocking, false));
    registerSetting(new BoolSetting("TransitionBlocking", "Sets transition blocking state", &transitionBlocking, false));
    registerSetting(new BoolSetting("BlockedUsingShield", "Sets blocked using shield state", &blockedUsingShield, false));
    registerSetting(new BoolSetting("BlockedUsingDamagedShield", "Sets blocked using damaged shield state", &blockedUsingDamagedShield, false));
    registerSetting(new BoolSetting("Sleeping", "Sets sleeping state", &sleeping, false));
    registerSetting(new BoolSetting("WantsToWake", "Sets wants to wake state", &wantsToWake, false));
    registerSetting(new BoolSetting("TradeInterest", "Sets trade interest state", &tradeInterest, false));
    registerSetting(new BoolSetting("DoorBreaker", "Enables door breaking", &doorBreaker, false));
    registerSetting(new BoolSetting("BreakingObstruction", "Sets breaking obstruction state", &breakingObstruction, false));
    registerSetting(new BoolSetting("DoorOpener", "Enables door opening", &doorOpener, false));
    registerSetting(new BoolSetting("IsIllagerCaptain", "Sets illager captain state", &isIllagerCaptain, false));
    registerSetting(new BoolSetting("Stunned", "Sets stunned state", &stunned, false));
    registerSetting(new BoolSetting("Roaring", "Sets roaring state", &roaring, false));
    registerSetting(new BoolSetting("DelayedAttack", "Sets delayed attack state", &delayedAttack, false));
    registerSetting(new BoolSetting("IsAvoidingMobs", "Sets avoiding mobs state", &isAvoidingMobs, false));
    registerSetting(new BoolSetting("IsAvoidingBlock", "Sets avoiding block state", &isAvoidingBlock, false));
    registerSetting(new BoolSetting("FacingTargetToRangeAttack", "Sets facing target for ranged attack", &facingTargetToRangeAttack, false));
    registerSetting(new BoolSetting("HiddenWhenInvisible", "Hides when invisible", &hiddenWhenInvisible, false));
    registerSetting(new BoolSetting("IsInUI", "Sets in UI state", &isInUi, false));
    registerSetting(new BoolSetting("Stalking", "Sets stalking state", &stalking, false));
    registerSetting(new BoolSetting("Emoting", "Sets emoting state", &emoting, false));
    registerSetting(new BoolSetting("Celebrating", "Sets celebrating state", &celebrating, false));
    registerSetting(new BoolSetting("Admiring", "Sets admiring state", &admiring, false));
    registerSetting(new BoolSetting("CelebratingSpecial", "Sets special celebrating state", &celebratingSpecial, false));
    registerSetting(new BoolSetting("OutOfControl", "Sets out of control state", &outOfControl, false));
    registerSetting(new BoolSetting("RamAttack", "Sets ram attack state", &ramAttack, false));
    registerSetting(new BoolSetting("PlayingDead", "Sets playing dead state", &playingDead, false));
    registerSetting(new BoolSetting("InAscendableBlock", "Sets in ascendable block state", &inAscendableBlock, false));
    registerSetting(new BoolSetting("OverDescendableBlock", "Sets over descendable block state", &overDescendableBlock, false));
    registerSetting(new BoolSetting("Croaking", "Sets croaking state", &croaking, false));
    registerSetting(new BoolSetting("EatMob", "Sets eat mob state", &eatMob, false));
    registerSetting(new BoolSetting("JumpGoalJump", "Sets jump goal jump state", &jumpGoalJump, false));
    registerSetting(new BoolSetting("Emerging", "Sets emerging state", &emerging, false));
    registerSetting(new BoolSetting("Sniffing", "Sets sniffing state", &sniffing, false));
    registerSetting(new BoolSetting("Digging", "Sets digging state", &digging, false));
    registerSetting(new BoolSetting("SonicBoom", "Sets sonic boom state", &sonicBoom, false));
    registerSetting(new BoolSetting("HasDashCooldown", "Sets dash cooldown state", &hasDashCooldown, false));
    registerSetting(new BoolSetting("PushTowardsClosestSpace", "Pushes towards closest space", &pushTowardsClosestSpace, false));
    registerSetting(new BoolSetting("Deprecated1", "Sets deprecated flag 1", &deprecated_1, false));
    registerSetting(new BoolSetting("Deprecated2", "Sets deprecated flag 2", &deprecated_2, false));
    registerSetting(new BoolSetting("Deprecated3", "Sets deprecated flag 3", &deprecated_3, false));
    registerSetting(new BoolSetting("Searching", "Sets searching state", &searching, false));
    registerSetting(new BoolSetting("Crawling", "Sets crawling state", &crawling, false));
    registerSetting(new BoolSetting("TimerFlag1", "Sets timer flag 1", &timerFlag_1, false));
    registerSetting(new BoolSetting("TimerFlag2", "Sets timer flag 2", &timerFlag_2, false));
    registerSetting(new BoolSetting("TimerFlag3", "Sets timer flag 3", &timerFlag_3, false));
    registerSetting(new BoolSetting("BodyRotationBlocked", "Blocks body rotation", &bodyRotationBlocked, false));


}

void Flags::onNormalTick(LocalPlayer* localPlayer) {
    if (!Game::getLocalPlayer()) return;
    if (onfire) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Onfire, true);
    if (sneaking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sneaking, true);
    if (riding) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Riding, true);
    if (sprinting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sprinting, true);
    if (usingitem) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Usingitem, true);
    if (invisible) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Invisible, true);
    if (tempted) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Tempted, true);
    if (inlove) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Inlove, true);
    if (saddled) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Saddled, true);
    if (powered) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Powered, true);
    if (ignited) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Ignited, true);
    if (baby) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Baby, true);
    if (converting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Converting, true);
    if (critical) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Critical, true);
    if (canShowName) Game::getLocalPlayer()->setStatusFlag(ActorFlags::CanShowName, true);
    if (alwaysShowName) Game::getLocalPlayer()->setStatusFlag(ActorFlags::AlwaysShowName, true);
    if (noai) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Noai, true);
    if (silent) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Silent, true);
    if (wallclimbing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Wallclimbing, true);
    if (canclimb) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Canclimb, true);
    if (canswim) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Canswim, true);
    if (canfly) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Canfly, true);
    if (canwalk) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Canwalk, true);
    if (resting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Resting, true);
    if (sitting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sitting, true);
    if (angry) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Angry, true);
    if (interested) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Interested, true);
    if (charged) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Charged, true);
    if (tamed) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Tamed, true);
    if (orphaned) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Orphaned, true);
    if (leashed) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Leashed, true);
    if (sheared) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sheared, true);
    if (gliding) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Gliding, true);
    if (elder) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Elder, true);
    if (moving) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Moving, true);
    if (breathing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Breathing, true);
    if (chested) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Chested, true);
    if (stackable) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Stackable, true);
    if (showBottom) Game::getLocalPlayer()->setStatusFlag(ActorFlags::ShowBottom, true);
    if (standing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Standing, true);
    if (shaking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Shaking, true);
    if (idling) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Idling, true);
    if (casting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Casting, true);
    if (charging) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Charging, true);
    if (wasdControlled) Game::getLocalPlayer()->setStatusFlag(ActorFlags::WasdControlled, true);
    if (canPowerJump) Game::getLocalPlayer()->setStatusFlag(ActorFlags::CanPowerJump, true);
    if (canDash) Game::getLocalPlayer()->setStatusFlag(ActorFlags::CanDash, true);
    if (lingering) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Lingering, true);
    if (hasCollision) Game::getLocalPlayer()->setStatusFlag(ActorFlags::HasCollision, true);
    if (hasGravity) Game::getLocalPlayer()->setStatusFlag(ActorFlags::HasGravity, true);
    if (fireImmune) Game::getLocalPlayer()->setStatusFlag(ActorFlags::FireImmune, true);
    if (dancing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Dancing, true);
    if (enchanted) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Enchanted, true);
    if (returntrident) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Returntrident, true);
    if (containerIsPrivate) Game::getLocalPlayer()->setStatusFlag(ActorFlags::ContainerIsPrivate, true);
    if (isTransforming) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsTransforming, true);
    if (damagenearbymobs) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Damagenearbymobs, true);
    if (swimming) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Swimming, true);
    if (bribed) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Bribed, true);
    if (isPregnant) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsPregnant, true);
    if (layingEgg) Game::getLocalPlayer()->setStatusFlag(ActorFlags::LayingEgg, true);
    if (passengerCanPick) Game::getLocalPlayer()->setStatusFlag(ActorFlags::PassengerCanPick, true);
    if (transitionSitting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TransitionSitting, true);
    if (eating) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Eating, true);
    if (layingDown) Game::getLocalPlayer()->setStatusFlag(ActorFlags::LayingDown, true);
    if (sneezing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sneezing, true);
    if (trusting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Trusting, true);
    if (rolling) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Rolling, true);
    if (scared) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Scared, true);
    if (inScaffolding) Game::getLocalPlayer()->setStatusFlag(ActorFlags::InScaffolding, true);
    if (overScaffolding) Game::getLocalPlayer()->setStatusFlag(ActorFlags::OverScaffolding, true);
    if (descendThroughBlock) Game::getLocalPlayer()->setStatusFlag(ActorFlags::DescendThroughBlock, true);
    if (blocking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Blocking, true);
    if (transitionBlocking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TransitionBlocking, true);
    if (blockedUsingShield) Game::getLocalPlayer()->setStatusFlag(ActorFlags::BlockedUsingShield, true);
    if (blockedUsingDamagedShield) Game::getLocalPlayer()->setStatusFlag(ActorFlags::BlockedUsingDamagedShield, true);
    if (sleeping) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sleeping, true);
    if (wantsToWake) Game::getLocalPlayer()->setStatusFlag(ActorFlags::WantsToWake, true);
    if (tradeInterest) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TradeInterest, true);
    if (doorBreaker) Game::getLocalPlayer()->setStatusFlag(ActorFlags::DoorBreaker, true);
    if (breakingObstruction) Game::getLocalPlayer()->setStatusFlag(ActorFlags::BreakingObstruction, true);
    if (doorOpener) Game::getLocalPlayer()->setStatusFlag(ActorFlags::DoorOpener, true);
    if (isIllagerCaptain) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsIllagerCaptain, true);
    if (stunned) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Stunned, true);
    if (roaring) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Roaring, true);
    if (delayedAttack) Game::getLocalPlayer()->setStatusFlag(ActorFlags::DelayedAttack, true);
    if (isAvoidingMobs) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsAvoidingMobs, true);
    if (isAvoidingBlock) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsAvoidingBlock, true);
    if (facingTargetToRangeAttack) Game::getLocalPlayer()->setStatusFlag(ActorFlags::FacingTargetToRangeAttack, true);
    if (hiddenWhenInvisible) Game::getLocalPlayer()->setStatusFlag(ActorFlags::HiddenWhenInvisible, true);
    if (isInUi) Game::getLocalPlayer()->setStatusFlag(ActorFlags::IsInUi, true);
    if (stalking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Stalking, true);
    if (emoting) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Emoting, true);
    if (celebrating) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Celebrating, true);
    if (admiring) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Admiring, true);
    if (celebratingSpecial) Game::getLocalPlayer()->setStatusFlag(ActorFlags::CelebratingSpecial, true);
    if (outOfControl) Game::getLocalPlayer()->setStatusFlag(ActorFlags::OutOfControl, true);
    if (ramAttack) Game::getLocalPlayer()->setStatusFlag(ActorFlags::RamAttack, true);
    if (playingDead) Game::getLocalPlayer()->setStatusFlag(ActorFlags::PlayingDead, true);
    if (inAscendableBlock) Game::getLocalPlayer()->setStatusFlag(ActorFlags::InAscendableBlock, true);
    if (overDescendableBlock) Game::getLocalPlayer()->setStatusFlag(ActorFlags::OverDescendableBlock, true);
    if (croaking) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Croaking, true);
    if (eatMob) Game::getLocalPlayer()->setStatusFlag(ActorFlags::EatMob, true);
    if (jumpGoalJump) Game::getLocalPlayer()->setStatusFlag(ActorFlags::JumpGoalJump, true);
    if (emerging) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Emerging, true);
    if (sniffing) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Sniffing, true);
    if (digging) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Digging, true);
    if (sonicBoom) Game::getLocalPlayer()->setStatusFlag(ActorFlags::SonicBoom, true);
    if (hasDashCooldown) Game::getLocalPlayer()->setStatusFlag(ActorFlags::HasDashCooldown, true);
    if (pushTowardsClosestSpace) Game::getLocalPlayer()->setStatusFlag(ActorFlags::PushTowardsClosestSpace, true);
    if (deprecated_1) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Deprecated_1, true);
    if (deprecated_2) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Deprecated_2, true);
    if (deprecated_3) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Deprecated_3, true);
    if (searching) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Searching, true);
    if (crawling) Game::getLocalPlayer()->setStatusFlag(ActorFlags::Crawling, true);
    if (timerFlag_1) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TimerFlag_1, true);
    if (timerFlag_2) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TimerFlag_2, true);
    if (timerFlag_3) Game::getLocalPlayer()->setStatusFlag(ActorFlags::TimerFlag_3, true);
    if (bodyRotationBlocked) Game::getLocalPlayer()->setStatusFlag(ActorFlags::BodyRotationBlocked, true);
}
//void Flags::onSendPacket(Packet* packet, bool& cancel) {
    //if (!packet) return;
    //if (packet->getId() == PacketID::PlayerAuthInput) {
        //PlayerAuthInputPacket* authPacket = (PlayerAuthInputPacket*)packet;
        //Game::getLocalPlayer()->setStatusFlag(ActorFlags::Damagenearbymobs, true);
        //authPacket->mInputData |= InputData::AutoJumpingInWater;
    //}
    //if (packet->getId() == PacketID::InventoryTransaction) {
        //InventoryTransactionPacket* invPkt = (InventoryTransactionPacket*)packet;
        //invPkt->isClientSide = true;
    //}
//}